/*
 * Qc API
 * QC API
 *
 * OpenAPI spec version: 2.0.1
 * Contact: cloudsupport@telestream.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.telestream.cloud.qc;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.telestream.cloud.qc.Job;

/**
 * JobsCollection
 */

public class JobsCollection {
  @SerializedName("jobs")
  private List<Job> jobs = null;

  @SerializedName("page")
  private Integer page = null;

  @SerializedName("per_page")
  private Integer perPage = null;

  @SerializedName("page_count")
  private Integer pageCount = null;

  @SerializedName("total_count")
  private Integer totalCount = null;

  public JobsCollection jobs(List<Job> jobs) {
    this.jobs = jobs;
    return this;
  }

  public JobsCollection addJobsItem(Job jobsItem) {
    if (this.jobs == null) {
      this.jobs = new ArrayList<Job>();
    }
    this.jobs.add(jobsItem);
    return this;
  }

   /**
   * Get jobs
   * @return jobs
  **/
  @ApiModelProperty(value = "")
  public List<Job> getJobs() {
    return jobs;
  }

  public void setJobs(List<Job> jobs) {
    this.jobs = jobs;
  }

  public JobsCollection page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * A number of the fetched page.
   * @return page
  **/
  @ApiModelProperty(value = "A number of the fetched page.")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public JobsCollection perPage(Integer perPage) {
    this.perPage = perPage;
    return this;
  }

   /**
   * A number of jobs per page.
   * @return perPage
  **/
  @ApiModelProperty(value = "A number of jobs per page.")
  public Integer getPerPage() {
    return perPage;
  }

  public void setPerPage(Integer perPage) {
    this.perPage = perPage;
  }

  public JobsCollection pageCount(Integer pageCount) {
    this.pageCount = pageCount;
    return this;
  }

   /**
   * A number of all pages.
   * @return pageCount
  **/
  @ApiModelProperty(value = "A number of all pages.")
  public Integer getPageCount() {
    return pageCount;
  }

  public void setPageCount(Integer pageCount) {
    this.pageCount = pageCount;
  }

  public JobsCollection totalCount(Integer totalCount) {
    this.totalCount = totalCount;
    return this;
  }

   /**
   * A number of all jobs stored in the db.
   * @return totalCount
  **/
  @ApiModelProperty(value = "A number of all jobs stored in the db.")
  public Integer getTotalCount() {
    return totalCount;
  }

  public void setTotalCount(Integer totalCount) {
    this.totalCount = totalCount;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    JobsCollection jobsCollection = (JobsCollection) o;
    return Objects.equals(this.jobs, jobsCollection.jobs) &&
        Objects.equals(this.page, jobsCollection.page) &&
        Objects.equals(this.perPage, jobsCollection.perPage) &&
        Objects.equals(this.pageCount, jobsCollection.pageCount) &&
        Objects.equals(this.totalCount, jobsCollection.totalCount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(jobs, page, perPage, pageCount, totalCount);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class JobsCollection {\n");
    
    sb.append("    jobs: ").append(toIndentedString(jobs)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    perPage: ").append(toIndentedString(perPage)).append("\n");
    sb.append("    pageCount: ").append(toIndentedString(pageCount)).append("\n");
    sb.append("    totalCount: ").append(toIndentedString(totalCount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

