/*
 * Flip API
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.telestream.cloud.flip;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * CloudNotificationSettingsEvents
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2017-11-15T18:18:06.971+01:00")
public class CloudNotificationSettingsEvents {
  @SerializedName("encoding_completed")
  private Boolean encodingCompleted = null;

  @SerializedName("encoding_progress")
  private Boolean encodingProgress = null;

  @SerializedName("video_created")
  private Boolean videoCreated = null;

  @SerializedName("video_encoded")
  private Boolean videoEncoded = null;

  public CloudNotificationSettingsEvents encodingCompleted(Boolean encodingCompleted) {
    this.encodingCompleted = encodingCompleted;
    return this;
  }

   /**
   * If set to &#x60;true&#x60;, a notification will be sent after an encoding becomes complete.
   * @return encodingCompleted
  **/
  @ApiModelProperty(required = true, value = "If set to `true`, a notification will be sent after an encoding becomes complete.")
  public Boolean getEncodingCompleted() {
    return encodingCompleted;
  }

  public void setEncodingCompleted(Boolean encodingCompleted) {
    this.encodingCompleted = encodingCompleted;
  }

  public CloudNotificationSettingsEvents encodingProgress(Boolean encodingProgress) {
    this.encodingProgress = encodingProgress;
    return this;
  }

   /**
   * If set to &#x60;true&#x60;, a notification will be sent after an encoding&#39;s progess changes.
   * @return encodingProgress
  **/
  @ApiModelProperty(required = true, value = "If set to `true`, a notification will be sent after an encoding's progess changes.")
  public Boolean getEncodingProgress() {
    return encodingProgress;
  }

  public void setEncodingProgress(Boolean encodingProgress) {
    this.encodingProgress = encodingProgress;
  }

  public CloudNotificationSettingsEvents videoCreated(Boolean videoCreated) {
    this.videoCreated = videoCreated;
    return this;
  }

   /**
   * If set to &#x60;true&#x60;, a notification will be sent after a video is created.
   * @return videoCreated
  **/
  @ApiModelProperty(required = true, value = "If set to `true`, a notification will be sent after a video is created.")
  public Boolean getVideoCreated() {
    return videoCreated;
  }

  public void setVideoCreated(Boolean videoCreated) {
    this.videoCreated = videoCreated;
  }

  public CloudNotificationSettingsEvents videoEncoded(Boolean videoEncoded) {
    this.videoEncoded = videoEncoded;
    return this;
  }

   /**
   * If set to &#x60;true&#x60;, a notification will be sent after a video is encoded.
   * @return videoEncoded
  **/
  @ApiModelProperty(required = true, value = "If set to `true`, a notification will be sent after a video is encoded.")
  public Boolean getVideoEncoded() {
    return videoEncoded;
  }

  public void setVideoEncoded(Boolean videoEncoded) {
    this.videoEncoded = videoEncoded;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CloudNotificationSettingsEvents cloudNotificationSettingsEvents = (CloudNotificationSettingsEvents) o;
    return Objects.equals(this.encodingCompleted, cloudNotificationSettingsEvents.encodingCompleted) &&
        Objects.equals(this.encodingProgress, cloudNotificationSettingsEvents.encodingProgress) &&
        Objects.equals(this.videoCreated, cloudNotificationSettingsEvents.videoCreated) &&
        Objects.equals(this.videoEncoded, cloudNotificationSettingsEvents.videoEncoded);
  }

  @Override
  public int hashCode() {
    return Objects.hash(encodingCompleted, encodingProgress, videoCreated, videoEncoded);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CloudNotificationSettingsEvents {\n");
    
    sb.append("    encodingCompleted: ").append(toIndentedString(encodingCompleted)).append("\n");
    sb.append("    encodingProgress: ").append(toIndentedString(encodingProgress)).append("\n");
    sb.append("    videoCreated: ").append(toIndentedString(videoCreated)).append("\n");
    sb.append("    videoEncoded: ").append(toIndentedString(videoEncoded)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

