/*
 * Flip API
 * Description
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.telestream.cloud.flip;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * CreateVideoBody
 */

public class CreateVideoBody {
  @SerializedName("source_url")
  private String sourceUrl = null;

  @SerializedName("profiles")
  private String profiles = null;

  @SerializedName("payload")
  private String payload = null;

  @SerializedName("pipeline")
  private String pipeline = null;

  @SerializedName("subtitle_files")
  private List<String> subtitleFiles = null;

  @SerializedName("extra_variables")
  private Map<String, String> extraVariables = null;

  @SerializedName("path_format")
  private String pathFormat = null;

  public CreateVideoBody sourceUrl(String sourceUrl) {
    this.sourceUrl = sourceUrl;
    return this;
  }

   /**
   * An URL pointing to a source file.
   * @return sourceUrl
  **/
  @ApiModelProperty(value = "An URL pointing to a source file.")
  public String getSourceUrl() {
    return sourceUrl;
  }

  public void setSourceUrl(String sourceUrl) {
    this.sourceUrl = sourceUrl;
  }

  public CreateVideoBody profiles(String profiles) {
    this.profiles = profiles;
    return this;
  }

   /**
   * Comma-separated list of profile names or IDs to be used during encoding. Alternatively, specify none so no encodings are created yet.
   * @return profiles
  **/
  @ApiModelProperty(value = "Comma-separated list of profile names or IDs to be used during encoding. Alternatively, specify none so no encodings are created yet.")
  public String getProfiles() {
    return profiles;
  }

  public void setProfiles(String profiles) {
    this.profiles = profiles;
  }

  public CreateVideoBody payload(String payload) {
    this.payload = payload;
    return this;
  }

   /**
   * Arbitrary string stored along the Video object.
   * @return payload
  **/
  @ApiModelProperty(value = "Arbitrary string stored along the Video object.")
  public String getPayload() {
    return payload;
  }

  public void setPayload(String payload) {
    this.payload = payload;
  }

  public CreateVideoBody pipeline(String pipeline) {
    this.pipeline = pipeline;
    return this;
  }

   /**
   * String-encoded JSON describing profiles pipeline.
   * @return pipeline
  **/
  @ApiModelProperty(value = "String-encoded JSON describing profiles pipeline.")
  public String getPipeline() {
    return pipeline;
  }

  public void setPipeline(String pipeline) {
    this.pipeline = pipeline;
  }

  public CreateVideoBody subtitleFiles(List<String> subtitleFiles) {
    this.subtitleFiles = subtitleFiles;
    return this;
  }

  public CreateVideoBody addSubtitleFilesItem(String subtitleFilesItem) {
    if (this.subtitleFiles == null) {
      this.subtitleFiles = new ArrayList<String>();
    }
    this.subtitleFiles.add(subtitleFilesItem);
    return this;
  }

   /**
   * A list of urls pointing to remote subtitle files.
   * @return subtitleFiles
  **/
  @ApiModelProperty(value = "A list of urls pointing to remote subtitle files.")
  public List<String> getSubtitleFiles() {
    return subtitleFiles;
  }

  public void setSubtitleFiles(List<String> subtitleFiles) {
    this.subtitleFiles = subtitleFiles;
  }

  public CreateVideoBody extraVariables(Map<String, String> extraVariables) {
    this.extraVariables = extraVariables;
    return this;
  }

  public CreateVideoBody putExtraVariablesItem(String key, String extraVariablesItem) {
    if (this.extraVariables == null) {
      this.extraVariables = new HashMap<String, String>();
    }
    this.extraVariables.put(key, extraVariablesItem);
    return this;
  }

   /**
   * Get extraVariables
   * @return extraVariables
  **/
  @ApiModelProperty(value = "")
  public Map<String, String> getExtraVariables() {
    return extraVariables;
  }

  public void setExtraVariables(Map<String, String> extraVariables) {
    this.extraVariables = extraVariables;
  }

  public CreateVideoBody pathFormat(String pathFormat) {
    this.pathFormat = pathFormat;
    return this;
  }

   /**
   * Get pathFormat
   * @return pathFormat
  **/
  @ApiModelProperty(value = "")
  public String getPathFormat() {
    return pathFormat;
  }

  public void setPathFormat(String pathFormat) {
    this.pathFormat = pathFormat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateVideoBody createVideoBody = (CreateVideoBody) o;
    return Objects.equals(this.sourceUrl, createVideoBody.sourceUrl) &&
        Objects.equals(this.profiles, createVideoBody.profiles) &&
        Objects.equals(this.payload, createVideoBody.payload) &&
        Objects.equals(this.pipeline, createVideoBody.pipeline) &&
        Objects.equals(this.subtitleFiles, createVideoBody.subtitleFiles) &&
        Objects.equals(this.extraVariables, createVideoBody.extraVariables) &&
        Objects.equals(this.pathFormat, createVideoBody.pathFormat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(sourceUrl, profiles, payload, pipeline, subtitleFiles, extraVariables, pathFormat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateVideoBody {\n");
    
    sb.append("    sourceUrl: ").append(toIndentedString(sourceUrl)).append("\n");
    sb.append("    profiles: ").append(toIndentedString(profiles)).append("\n");
    sb.append("    payload: ").append(toIndentedString(payload)).append("\n");
    sb.append("    pipeline: ").append(toIndentedString(pipeline)).append("\n");
    sb.append("    subtitleFiles: ").append(toIndentedString(subtitleFiles)).append("\n");
    sb.append("    extraVariables: ").append(toIndentedString(extraVariables)).append("\n");
    sb.append("    pathFormat: ").append(toIndentedString(pathFormat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

