/*
 * Flip API
 * Description
 *
 * OpenAPI spec version: 2.0.1
 * Contact: cloudsupport@telestream.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.telestream.cloud.flip;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * FactorySync
 */

public class FactorySync {
  /**
   * Determines whether a Factory will be synchronised with an input bucket.
   */
  @JsonAdapter(SyncingEnum.Adapter.class)
  public enum SyncingEnum {
    STARTING("starting"),
    
    ALREADY_STARTED("already_started");

    private String value;

    SyncingEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static SyncingEnum fromValue(String text) {
      for (SyncingEnum b : SyncingEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<SyncingEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final SyncingEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public SyncingEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return SyncingEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("syncing")
  private SyncingEnum syncing = null;

  public FactorySync syncing(SyncingEnum syncing) {
    this.syncing = syncing;
    return this;
  }

   /**
   * Determines whether a Factory will be synchronised with an input bucket.
   * @return syncing
  **/
  @ApiModelProperty(value = "Determines whether a Factory will be synchronised with an input bucket.")
  public SyncingEnum getSyncing() {
    return syncing;
  }

  public void setSyncing(SyncingEnum syncing) {
    this.syncing = syncing;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    FactorySync factorySync = (FactorySync) o;
    return Objects.equals(this.syncing, factorySync.syncing);
  }

  @Override
  public int hashCode() {
    return Objects.hash(syncing);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class FactorySync {\n");
    
    sb.append("    syncing: ").append(toIndentedString(syncing)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

