/*
 * Flip API
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.telestream.cloud.flip;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import net.telestream.cloud.flip.Profile;

/**
 * PaginatedWorkflowsCollection
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-05T16:30:52.273+01:00")
public class PaginatedWorkflowsCollection {
  @SerializedName("workflows")
  private List<Profile> workflows = null;

  @SerializedName("page")
  private Integer page = null;

  @SerializedName("per_page")
  private Integer perPage = null;

  @SerializedName("total")
  private Integer total = null;

  public PaginatedWorkflowsCollection workflows(List<Profile> workflows) {
    this.workflows = workflows;
    return this;
  }

  public PaginatedWorkflowsCollection addWorkflowsItem(Profile workflowsItem) {
    if (this.workflows == null) {
      this.workflows = new ArrayList<Profile>();
    }
    this.workflows.add(workflowsItem);
    return this;
  }

   /**
   * Get workflows
   * @return workflows
  **/
  @ApiModelProperty(value = "")
  public List<Profile> getWorkflows() {
    return workflows;
  }

  public void setWorkflows(List<Profile> workflows) {
    this.workflows = workflows;
  }

  public PaginatedWorkflowsCollection page(Integer page) {
    this.page = page;
    return this;
  }

   /**
   * A number of the fetched page.
   * @return page
  **/
  @ApiModelProperty(value = "A number of the fetched page.")
  public Integer getPage() {
    return page;
  }

  public void setPage(Integer page) {
    this.page = page;
  }

  public PaginatedWorkflowsCollection perPage(Integer perPage) {
    this.perPage = perPage;
    return this;
  }

   /**
   * A number of factories per page.
   * @return perPage
  **/
  @ApiModelProperty(value = "A number of factories per page.")
  public Integer getPerPage() {
    return perPage;
  }

  public void setPerPage(Integer perPage) {
    this.perPage = perPage;
  }

  public PaginatedWorkflowsCollection total(Integer total) {
    this.total = total;
    return this;
  }

   /**
   * A number of all factories stored in the db.
   * @return total
  **/
  @ApiModelProperty(value = "A number of all factories stored in the db.")
  public Integer getTotal() {
    return total;
  }

  public void setTotal(Integer total) {
    this.total = total;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaginatedWorkflowsCollection paginatedWorkflowsCollection = (PaginatedWorkflowsCollection) o;
    return Objects.equals(this.workflows, paginatedWorkflowsCollection.workflows) &&
        Objects.equals(this.page, paginatedWorkflowsCollection.page) &&
        Objects.equals(this.perPage, paginatedWorkflowsCollection.perPage) &&
        Objects.equals(this.total, paginatedWorkflowsCollection.total);
  }

  @Override
  public int hashCode() {
    return Objects.hash(workflows, page, perPage, total);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaginatedWorkflowsCollection {\n");
    
    sb.append("    workflows: ").append(toIndentedString(workflows)).append("\n");
    sb.append("    page: ").append(toIndentedString(page)).append("\n");
    sb.append("    perPage: ").append(toIndentedString(perPage)).append("\n");
    sb.append("    total: ").append(toIndentedString(total)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
  
}

