/*
 * IAM API
 * IAM API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cloudsupport@telestream.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.telestream.cloud.iam;

import net.telestream.cloud.iam.ApiException;
import net.telestream.cloud.iam.Credential;
import net.telestream.cloud.iam.CredentialsResponse;
import net.telestream.cloud.iam.Error;
import net.telestream.cloud.iam.StatementsList;
import org.junit.Test;
import org.junit.Ignore;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for IamApi
 */
@Ignore
public class IamApiTest {

    private final IamApi api = new IamApi();

    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void deleteCredentialTest() throws ApiException {
        String id = null;
        api.deleteCredential(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCredentialTest() throws ApiException {
        String id = null;
        Credential response = api.getCredential(id);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getCredentialsTest() throws ApiException {
        CredentialsResponse response = api.getCredentials();

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void getPolicyTest() throws ApiException {
        StatementsList policy = null;
        Map<String, Boolean> response = api.getPolicy(policy);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void postCredentialsTest() throws ApiException {
        Credential createCredential = null;
        Credential response = api.postCredentials(createCredential);

        // TODO: test validations
    }
    
    /**
     * 
     *
     * 
     *
     * @throws ApiException
     *          if the Api call fails
     */
    @Test
    public void updateCredentialTest() throws ApiException {
        String id = null;
        Credential updateCredential = null;
        Credential response = api.updateCredential(id, updateCredential);

        // TODO: test validations
    }
    
}
