/*
 * Notifications API
 * Notifications API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.telestream.cloud.notifications;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Params
 */

public class Params {
  @SerializedName("addresses")
  private List<String> addresses = null;

  @SerializedName("url")
  private String url = null;

  /**
   * #webhook  \&quot;HTTP method\&quot; 
   */
  @JsonAdapter(MethodEnum.Adapter.class)
  public enum MethodEnum {
    GET("get"),
    
    POST("post");

    private String value;

    MethodEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static MethodEnum fromValue(String text) {
      for (MethodEnum b : MethodEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<MethodEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final MethodEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public MethodEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return MethodEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("method")
  private MethodEnum method = null;

  @SerializedName("retries")
  private Integer retries = null;

  public Params addresses(List<String> addresses) {
    this.addresses = addresses;
    return this;
  }

  public Params addAddressesItem(String addressesItem) {
    if (this.addresses == null) {
      this.addresses = new ArrayList<String>();
    }
    this.addresses.add(addressesItem);
    return this;
  }

   /**
   * #email  E-mail address 
   * @return addresses
  **/
  @ApiModelProperty(value = "#email  E-mail address ")
  public List<String> getAddresses() {
    return addresses;
  }

  public void setAddresses(List<String> addresses) {
    this.addresses = addresses;
  }

  public Params url(String url) {
    this.url = url;
    return this;
  }

   /**
   * #webhook  \&quot;Webhook URL\&quot; 
   * @return url
  **/
  @ApiModelProperty(value = "#webhook  \"Webhook URL\" ")
  public String getUrl() {
    return url;
  }

  public void setUrl(String url) {
    this.url = url;
  }

  public Params method(MethodEnum method) {
    this.method = method;
    return this;
  }

   /**
   * #webhook  \&quot;HTTP method\&quot; 
   * @return method
  **/
  @ApiModelProperty(value = "#webhook  \"HTTP method\" ")
  public MethodEnum getMethod() {
    return method;
  }

  public void setMethod(MethodEnum method) {
    this.method = method;
  }

  public Params retries(Integer retries) {
    this.retries = retries;
    return this;
  }

   /**
   * #webhook  \&quot;Number of attempts before forgetting the notification\&quot; 
   * @return retries
  **/
  @ApiModelProperty(value = "#webhook  \"Number of attempts before forgetting the notification\" ")
  public Integer getRetries() {
    return retries;
  }

  public void setRetries(Integer retries) {
    this.retries = retries;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Params params = (Params) o;
    return Objects.equals(this.addresses, params.addresses) &&
        Objects.equals(this.url, params.url) &&
        Objects.equals(this.method, params.method) &&
        Objects.equals(this.retries, params.retries);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addresses, url, method, retries);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Params {\n");
    
    sb.append("    addresses: ").append(toIndentedString(addresses)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    retries: ").append(toIndentedString(retries)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

