/*
 * Notifications API
 * Notifications API
 *
 * OpenAPI spec version: 2.0.0
 * Contact: cloudsupport@telestream.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.telestream.cloud.notifications;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Topic
 */

public class Topic {
  @SerializedName("account")
  private String account = null;

  /**
   * [required] Name of service 
   */
  @JsonAdapter(ServiceEnum.Adapter.class)
  public enum ServiceEnum {
    QC("qc");

    private String value;

    ServiceEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ServiceEnum fromValue(String text) {
      for (ServiceEnum b : ServiceEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<ServiceEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ServiceEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ServiceEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return ServiceEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("service")
  private ServiceEnum service = null;

  /**
   * [required] Name of the event;  Quality Control (video-passed,  video-error,  video-warning,  video-rejected,  video-canceled) 
   */
  @JsonAdapter(EventEnum.Adapter.class)
  public enum EventEnum {
    PASSED("video-passed"),
    
    ERROR("video-error"),
    
    WARNING("video-warning"),
    
    REJECTED("video-rejected"),
    
    CANCELED("video-canceled");

    private String value;

    EventEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static EventEnum fromValue(String text) {
      for (EventEnum b : EventEnum.values()) {
        if (String.valueOf(b.value).equals(text)) {
          return b;
        }
      }
      return null;
    }

    public static class Adapter extends TypeAdapter<EventEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final EventEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public EventEnum read(final JsonReader jsonReader) throws IOException {
        String value = jsonReader.nextString();
        return EventEnum.fromValue(String.valueOf(value));
      }
    }
  }

  @SerializedName("event")
  private EventEnum event = null;

  @SerializedName("project")
  private String project = null;

   /**
   * [read-only] Account identifier connected to subscription notification 
   * @return account
  **/
  @ApiModelProperty(value = "[read-only] Account identifier connected to subscription notification ")
  public String getAccount() {
    return account;
  }

  public Topic service(ServiceEnum service) {
    this.service = service;
    return this;
  }

   /**
   * [required] Name of service 
   * @return service
  **/
  @ApiModelProperty(value = "[required] Name of service ")
  public ServiceEnum getService() {
    return service;
  }

  public void setService(ServiceEnum service) {
    this.service = service;
  }

  public Topic event(EventEnum event) {
    this.event = event;
    return this;
  }

   /**
   * [required] Name of the event;  Quality Control (video-passed,  video-error,  video-warning,  video-rejected,  video-canceled) 
   * @return event
  **/
  @ApiModelProperty(value = "[required] Name of the event;  Quality Control (video-passed,  video-error,  video-warning,  video-rejected,  video-canceled) ")
  public EventEnum getEvent() {
    return event;
  }

  public void setEvent(EventEnum event) {
    this.event = event;
  }

  public Topic project(String project) {
    this.project = project;
    return this;
  }

   /**
   * [required] Project ID 
   * @return project
  **/
  @ApiModelProperty(value = "[required] Project ID ")
  public String getProject() {
    return project;
  }

  public void setProject(String project) {
    this.project = project;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Topic topic = (Topic) o;
    return Objects.equals(this.account, topic.account) &&
        Objects.equals(this.service, topic.service) &&
        Objects.equals(this.event, topic.event) &&
        Objects.equals(this.project, topic.project);
  }

  @Override
  public int hashCode() {
    return Objects.hash(account, service, event, project);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Topic {\n");
    
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    service: ").append(toIndentedString(service)).append("\n");
    sb.append("    event: ").append(toIndentedString(event)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

