/*
 * Tts API
 * Description
 *
 * OpenAPI spec version: 3.1.0
 * Contact: cloudsupport@telestream.net
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package net.telestream.cloud.tts;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * Corpus
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-01-09T13:44:56.229+01:00")
public class Corpus {
  @SerializedName("name")
  private String name = null;

  @SerializedName("status")
  private String status = null;

  public Corpus name(String name) {
    this.name = name;
    return this;
  }

   /**
   * The name of the Corpus.
   * @return name
  **/
  @ApiModelProperty(example = "file-name", value = "The name of the Corpus.")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public Corpus status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Determines the status of the Corpus.
   * @return status
  **/
  @ApiModelProperty(example = "being_processed", value = "Determines the status of the Corpus.")
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Corpus corpus = (Corpus) o;
    return Objects.equals(this.name, corpus.name) &&
        Objects.equals(this.status, corpus.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Corpus {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

